tripods:
  unloading: 2       # количество штативов для загрузки пробирок
  loading: 7         # количество штативов для выгрузки пробирок

racks:
  loading_zone: 50     # количество позиций рэков в зоне загрузки
  unloading_zone: 50   # количество позиций рэков в зоне выгрузки